hl.env("XCURSOR_SIZE", 24)
hl.env("XCURSOR_THEME", "Aki-Aspen")
hl.env("GTK_ICON_THEME","MacTahoe-dark")
hl.env("QT_ICON_THEME","MacTahoe-dark")
hl.env("QT_QPA_PLATFORMTHEME","qt6ct")   
hl.env("QT_STYLE_SHEET","/home/kelian/.config/dolphin-tahoe-dark.qss")
