-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    decoration = {
        rounding = 10,
        rounding_power = 10,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = false,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },

        blur = {
            enabled = true,
            size = 8,
            passes = 3,
            noise = 0.012,
            contrast = 0.9,
            brightness = 0.85,
            xray = false,
            new_optimizations = true,
            special = false
        },
    },
})

hl.layer_rule({ match = { namespace = "quickshell:notifpopup" }, blur = true,ignore_alpha = 0.5, })
hl.layer_rule({ match = { namespace = "quickshell:notifcenter" }, blur = true, ignore_alpha = 0.5 })
hl.layer_rule({ match = { namespace = "quickshell:ai" }, blur = true, ignore_alpha = 0,1})
